# Generated by Django 5.0.3 on 2024-04-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangalibe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Choice',
        ),
    ]
